### ISSUE TITLE
"Copy Another Library" functionality broken

### ISSUE THREAD

**Issue by antnazNaz** [jimmejardine/qiqqa-open-source#134]
In the process of converting my v79 to v82pre4, old web libraries are functioning well and are locally stored. When creating a new intranet library, copying from other libraries does not do anything - nothing gets transferred, no messages.

**Comment by antnazNaz** [comment]
Going into the original library and copying item-by-item also doesn't copy those records to the destination intranet library.

**Comment by antnazNaz** [comment]
I tried both ways and neither of those options worked. Moving also didn't work. I thought maybe it was due to an issue with a legacy web library so I tried to copy a fresh pdf between two newly created intranet (dropbox) libraries. It didn't work...

Also... glad you're so committed to Qiqqa - it's a great tool and I do my best to get others to use it instead of **subpar** alternatives like M#@$lay or Z##$#$ro

**Comment by antnazNaz** [comment]
I also went through the effort to uninstall and reinstall Qiqqa pre5, while deleting the AppData folder. Issue remains.

**Comment by antnazNaz** [comment]
Well, good news - it works with 82pre3 but not pre4 or pre5. So there's a regression bug somewhere in pre4 code.

**Comment by GerHobbelt** [comment]
🤔 🤔  That's nasty. Hadn't expected that regression. I wonder why it happened. 🤔 Thanks for testing the versions, by the way. 

It may take a few days and I may pester you for a couple of screenshots or directory dumps if you're available for testing then (dev effort fluctuates per day, depending on RL priorities; tomorrow is expected to be a busy day, so less time to dig into this)

Anyway, if I create a new prerelease to test this, I'll signal you via this issue, so you can test any changes I make. Testing those would be highly appreciated.

> And thanks for the thumbs up, indeed Zotero et al didn't fly for me either. Though I must say that the last year with v79 was an enormous pain as my search index broke down and I couldn't get it back up until Qiqqa went Open Source - another project of mine on github shows the reverse engineering process and data-dumping I did before that time as I needed the Qiqqa Sniffer and an external search engine to make it work for me. 😱   Oh, the fun. \[/rant\]

**Comment by antnazNaz** [comment]
Happy to assist any way I can 👍

**Comment by GerHobbelt** [comment]
Did a test with bleeding edge code: I can confirm the bug. 👍

**Comment by GerHobbelt** [comment]
@antnazNaz : there's a new v82pre6 prerelease installer available at https://github.com/GerHobbelt/qiqqa-open-source/releases/tag/v82.0.7222.1299 which should fix this copy/move documents issue.

Much appreciated if you could test-fly that one and see if the problem is truly resolved. 😁

**Comment by antnazNaz** [comment]
Works well! Thanks
