### ISSUE TITLE
nvm-windows doesn't install npm?

### ISSUE THREAD

**Issue by SimonDedman** [jimmejardine/qiqqa-open-source#151]
Hi guys, sorry if this is basic, I'm not used to building packages in windows. In the developer info page on the web, mandatory is to install node & nvm preferably via Corey's package, however when I run "npm i" in the correct folder it returns 

"'npm' is not recognized as an internal or external command, operable program or batch file."

Suggesting npm isn't installed. "nvm i" returns a list of commands one can use with nvm but doesn't look to do anything per se. Subsequently trying to Rebuild Solution fails with loads of missing files. It says project references NuGet packages that are missing before I Rebuild, and 122 errors 134 warnings mostly about missing files when I do Rebuild, e.g.
Metadata file 'C:\Program Files (x86)\Qiqqa\QiqqaTestHelpers\bin\Release\QiqqaTestHelpers.dll' could not be found

Any advice very much appreciated. Thanks in advance.

**Comment by SimonDedman** [comment]
Edit: I only just found the setup80.exe file on the second page of the open source releases. When one clicks the link on the Github homepage:

"Qiqqa Open Source software installer releases are available in the mainstream repository. Here's where you'll find Qiqqa v80 and later"

It goes to the releases page, which lists all the build-from-source point releases - v80 setup.exe isn't until the next page, after v79 on the first page, which is unintuitive and may confuse others also. ANy chance that homepage link could point to:

https://github.com/jimmejardine/qiqqa-open-source/releases/tag/v80

or indeed directly to:

https://github.com/jimmejardine/qiqqa-open-source/releases/download/v80/setup80.exe

? Cheers for all you guys are doing!

**Comment by GerHobbelt** [comment]
And if you feel adventurous, there's the alpha/beta releases  at https://github.com/GerHobbelt/qiqqa-open-source/releases -- (Note: the BibTeX editor in those prereleases is a bother, so re-install v80 when you need that one to be smooth enough for daily work.)

**Comment by SimonDedman** [comment]
All working with v80 & subsequent prereleases.
