### ISSUE TITLE
Can Qiqqa be using DOI sniffing as well?

### ISSUE THREAD

**Issue by wkedziora** [jimmejardine/qiqqa-open-source#153]
I have just started using Qiqqa and I like it a lot. 
However, because I migrated from Mendeley I think it might have one big advantage: searching for DOI for an article. 
Is there a possibility that DOI field in document properties would allow for DOI sniff similar to Bibtex?

Like described here:
https://stackoverflow.com/questions/10507049/get-metadata-from-doi

**Comment by GerHobbelt** [comment]
Haven't used DOI myself yet, and Qiqqa doesn't auto-extract DOI from PDF documents yet, so that bit of workflow would also need some work.

Thanks for the pullreq, BTW. 👍
