### ISSUE TITLE
url

### ISSUE THREAD

**Issue by Swatchel** [jimmejardine/qiqqa-open-source#158]
url http://download.microsoft.com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe is unreachable now.
Please fix this url in your code

**Comment by GerHobbelt** [comment]
If it'd be that easy 😉 

Relevant materials:

- https://github.com/domgho/innodependencyinstaller/commit/ce85626e61cc9e1dacb9578e8e04ab9d435d9edc#r16322373-permalink
- https://github.com/domgho/innodependencyinstaller/issues/12
- Hunting down isxdl.dll:
  +  http://www.istool.net/downloads.html 
  +  https://stackoverflow.com/questions/6076427/running-setup-exe-created-by-inno-setup-and-get-isxdl-dll-was-not-found#6189026 

Preliminary conclusion: ISXDL.dll for InnoSetup doesn't seem to support HTTPS and this (and other) old downloads have migrated to HTTPS URLs.



---

The overarching question, by the way, is whether we should bother with this at all, as the .NET code is only supported on Microsoft-supported platforms anyway: .NET 4.6+ is Windows 7 and above and this stuff is for obsoleted platforms WinXP/Win9x AFAICT.

**Comment by GerHobbelt** [comment]
Hm 🤔   Hadn't realized we've got seagull style processing on github too: https://github.com/Swatchel?tab=overview&from=2020-02-01&to=2020-02-29 - that's 115 issues, all copy/paste one and the same, no follow-up, i.e. no responses from the source after that day. 🤡 

Closing this.  Antiquated.
