### ISSUE TITLE
BUG: The pdf reading screen has an odd-looking blank space in the right-side panel

### ISSUE THREAD

**Issue by raindropsfromsky** [jimmejardine/qiqqa-open-source#181]
There is an odd open space in the right-hand panel, in the pdf reading screen.

![image](https://user-images.githubusercontent.com/9047168/77563919-ef544700-6ee7-11ea-942b-b53cda7e2e02.png)

**Comment by GerHobbelt** [comment]
Correct. That's still a bit hacky but previously it displayed a message about the PDF having been deleted, which is only applicable in certain other circumstances when where this view is re-used within Qiqqa.

**Comment by GerHobbelt** [comment]
Fixed by the work done by @mahfiaz, which has been integrated in prerelease https://github.com/GerHobbelt/qiqqa-open-source/releases/tag/v82.0.7555-31312
