### ISSUE TITLE
Qiqqa citation problem - diacritic signs

### ISSUE THREAD

**Issue by wkedziora** [jimmejardine/qiqqa-open-source#201]
When taking an article, e.g.:
![Qiqqa_title](https://user-images.githubusercontent.com/9574956/78884259-ed979100-7a5a-11ea-9e3b-5953a74368e7.PNG)

I am doing BibTex Sniff and checking the properties reveals a problem:
![Qiqqa_properties2](https://user-images.githubusercontent.com/9574956/78884547-63036180-7a5b-11ea-9af3-f987193392e1.png)

And when I want to cite that item I get a problem:
![Qiqqa_citation2](https://user-images.githubusercontent.com/9574956/78884558-672f7f00-7a5b-11ea-987d-0848b278b3eb.png)

The BibTex for this file looks like:
`@article{Bielinis2019,
  doi = {10.3390/f10100827},
  url = {https://doi.org/10.3390/f10100827},
  year = {2019},
  month = sep,
  publisher = {{MDPI} {AG}},
  volume = {10},
  number = {10},
  pages = {827},
  author = {Bielinis and  {\L}ukowski and  Omelan and  Boiko and  Takayama and  Grebner},
  title = {The Effect of Recreation in a Snow-Covered Forest Environment on the Psychological Wellbeing of Young Adults: Randomized Controlled Study},
  journal = {Forests}
}`

The {\L} entry in BibTex is used correctly. When I change {\L} into Ł it works fine, but needs manual changes.

**Comment by mahfiaz** [comment]
Here is a short list of common LaTeX symbols in BibTeX: http://www.bibtex.org/SpecialSymbols/

**Comment by wkedziora** [comment]
Thanks for that, I have check most of them and they work flawlessly. This one (Ł or ł) seems not...

**Comment by mahfiaz** [comment]
I added support for more special characters. Let's hope it didn't introduce new bugs.
https://github.com/mahfiaz/qiqqa-open-source/commit/21b43febd0f5b9542908b59a9e2dfc709a087b4d

**Comment by GerHobbelt** [comment]
This particular issue should be fixed in the latest release: https://github.com/GerHobbelt/qiqqa-open-source/releases/tag/v82.0.7568-29227

(More specifically, it should be fixed since this release: https://github.com/GerHobbelt/qiqqa-open-source/releases/tag/v82.0.7555-31312 though this issue is not listed as 'fixed' in the changelog there.)
