### ISSUE TITLE
Kick out Sorax closed source commercial library which is not updated unless I put down $$$ for them.

### ISSUE THREAD

**Issue by GerHobbelt** [jimmejardine/qiqqa-open-source#209]
Follow-up on #136 et al: moving from Sorax to MuPDF for page rendering.

---

I'm rather more intent on kicking out Sorax and going with MuPDF (and MuPDFSharp) as that's open source instead of closed source, so easier to dive in and debug. Sorax, as far as I am concerned, is a dead end that's needed until I have plugged in MuPDF for page rendering.

Regarding slow speed problems of MuPDF: those are different, but do exist: https://bugs.ghostscript.com/show_bug.cgi?id=701945#c2

**Comment by GerHobbelt** [comment]
When this done, this also should fix #7 -- doublecheck with the [Evil PDF Collection](https://github.com/GerHobbelt/Evil-PDF-Library-for-Qiqqa)

**Comment by mahfiaz** [comment]
SumatraPDF is lightning fast, uses MuPDF and is open source, so it probably can be used as a code example: https://github.com/sumatrapdfreader/sumatrapdf

**Comment by GerHobbelt** [comment]
@mahfiaz et al: good suggestion. I did already look at mupdf etc, see the notes I wrote some time ago in the docs-src directory:

- https://github.com/jimmejardine/qiqqa-open-source/blob/master/docs-src/Progress%20In%20Development%20-%20Towards%20Migrating%20the%20PDF%20Viewer%20%2B%20Renderer%20(%2B%20Text%20Extractor).md
- https://github.com/jimmejardine/qiqqa-open-source/blob/master/docs-src/Progress%20In%20Development%20-%20Notes%20From%20The%20Trenches%20-%20Odd%2C%20Odder%2C%20Oddest%2C%20...PDF!.md

These may be of interest for others looking into text extraction from pdf using open source (and some commercial tools - need to complete the latter tests and write about the findings there.)

**Comment by jimme-jamatto** [comment]
most of my time in qiqqa went into getting pdf rendering to be 'cheap enough' and 'functional enough' and 'fast enough'.  it seemed that never the three could meet in one product!

sorax was by far the only PDF renderer that managed to render 'most' PDFs.  they were very good at the time too when i would email them a 'unrenderable' pdf, they would turn around a bugfix pretty quickly.  i wonder if you couldn't approach them down the line and ask for an opensource licence to their latest and greatest (if they are still a going concern)?

**Comment by GerHobbelt** [comment]
Hi Jimme, just a quick copy&paste from #215:

---

(Also @jimmejardine, BTW) I just went and checked: SORAX seems DIW: http://www.soraxsoft.com/ seems to be the originator of the PDF render lib in Qiqqa (SORAX Software PDF Reader library) and MS Visual Studio Marketplace doesn't give a hit, while the Goolgy Interwebz produce http://www.soraxsoft.com/ as the company URL via various shareware download sites, where my box reports that URL as unreachable due to DNS issues, which reads to me like an expired/defunct company. Can anyone improve / correct this finding? (Start with Qiqqa's SPDF.DLL, which is the actual native lib we use; it's in /bin/ in the repo -- DLL Properties inspection lists that one as (c) 2011 which is spot one vs the SORAX PDF Reader hits I find on the net, which link to the unreachable http://www.soraxsoft.com/)

---

Seems to me SORAX is not operational anymore? 🤔 

Anyway, my basic stance on libraries to use in any software project is mentioned in that #215 blurb: I'm fine with anything **that comes with full source code and is user-recompilable** -- yes, I've been treated to source escrow and "full source" commercial libraries which turned out not to be able to recompile all or part of their functionality using the provided Makefiles or other build scripts at several times in my career: the hassles resulting from those folks' deliverables has taught me a very painful lesson: I'dd rather pick up abandonware with source than a commercial lib without. (Unless there are overarching conditions, e.g. a reduced software lifetime or particular customer demands 😉 )

See https://github.com/jimmejardine/qiqqa-open-source/blob/master/docs-src/Progress%20In%20Development%20-%20Towards%20Migrating%20the%20PDF%20Viewer%20%2B%20Renderer%20(%2B%20Text%20Extractor).md for some notes on my R&D to replace Sorax in 2020 A.D.

Not a smooth path as I'd initially hoped, alas.

**Comment by GerHobbelt** [comment]
SORAX is dead. Long live SORAX. 

But only in bleeding edge (master branch) and there's still plenty of work to do before the `mupdf` image renderer is made adequately responsive -- I blew away the (suboptimal) caches and now have a bare bones system working.

TODO: priority queue and central/global image cache (with ageing and resizing images when smaller versions are requested: that should take care of at least *some* "thumbnails" in the right sidebar causing even more mupdf/mudraw work.
TODO: make this exe invocation stuff a local server instead, so we can at least spare ourselves some of that exe startup cost for every image rendered.

Anyway, that TODO stuff can be filed in future issues.
 
This one is finally nuked. And SORAX is not coming back.

**Comment by klmckinney** [comment]
Hi @GerHobbelt ,   
How is the MuPDF work going?
Can I help?
