### ISSUE TITLE
Have you considered adding CUDA/Vulcan/OpenCL?

### ISSUE THREAD

**Issue by ljlueloff** [jimmejardine/qiqqa-open-source#216]
For users with extremely large libraries I don't know if they have crash issues like me, but considering that most modern systems have fairly decent GPUs with most Intel and AMD platforms even coming with embedded GPUs, I think having an option to enable processing via CUDA for NVIDIA, and Vulcan/OpenCL for others would be a great idea.  It would also boost your Elastic Search...

**Comment by ljlueloff** [comment]
Guess not?

**Comment by GerHobbelt** [comment]
Umm, I don't know how CUDA or OpenCL would significantly contribute to remove performance bottlenecks in Qiqqa for large libraries. 

I have a 40K+ document lib myself and there are several performance issues I identified with that one (PDF OCR, PDF text extraction (as the first stage of indexing), UI performance of the library overview/document list, ...) and I'm not sure how CUA/OpenCL would help to speed up an application like this as the biggest potential win would be "porting" the PDF parser/renderer to OpenCL while PDF processing, AFAICT, is not easily suitable for GPU style multiprocessing. Given #209, #34 and friends, there's quite some work to be done before this, probably?

Qiqqa doesn't employ Elastic Search but uses a Lucene based text search index, so are you addressing Qiqqa or maybe something else?

**Comment by GerHobbelt** [comment]
Closing as inactive, while the issues discussed here are listed in other tickets as well (apart from the CUDA, etc. suggestions, which currently are not feasible as mentioned above)
