### ISSUE TITLE
Fresh install, no idea what's wrong: making an annotation causes crash

### ISSUE THREAD

**Issue by jtgav** [jimmejardine/qiqqa-open-source#236]
I just installed Qiqqa open-source then I exported my bibtex from Mendeley. When I tried to make an annotation report to test the software, I encountered this error. 
![Untitled](https://user-images.githubusercontent.com/72382204/95060318-b6195100-072c-11eb-8024-ecde625f3cfb.png)
I don't have any idea at programming and I don't know what's wrong (Sometimes the software crashes after the error, sometimes it doesn't.) Thanks for all your help

**Comment by jtgav** [comment]
I was first using 82pre4 (thought it was the latest) but the issue persists at 82pre6. I am not a coder so I don't really know what's going on :(

**Comment by GerHobbelt** [comment]
Looking into it.

Latest Qiqqa is v82pre9, available at https://github.com/GerHobbelt/qiqqa-open-source/releases/tag/v82.0.7357.40407

**Comment by jtgav** [comment]
Awesome! I installed the updated version and it still happens.

Thank you for all your help!!!
