### ISSUE TITLE
Unhandled Exception: GDI+ error

### ISSUE THREAD

**Issue by GerHobbelt** [jimmejardine/qiqqa-open-source#244]
VERY probably the antique Gecko kicking up a ruckus as I was quickly clicking through the search engine tabs in the Sniffer as it happened:

![image](https://user-images.githubusercontent.com/402462/95505795-3ea72400-09af-11eb-9522-533fc4a1da74.png)

![image](https://user-images.githubusercontent.com/402462/95505827-4a92e600-09af-11eb-908d-e71de0aaf19b.png)

Hence related to #2 ...

**Comment by mahfiaz** [comment]
I think the sniffer should be a part of a regular Chrome and Firefox browser plugin for Qiqqa.

**Comment by GerHobbelt** [comment]
@mahfiaz: agree, but then I'd have to recreate the PDF view + copy/paste/search UI in a browser plugin (the upper half of the Qiqqa Sniffer dialog, more or less) and that's not a motivating thought. 🤡 

Am considering other ways to modernize this embedded browser conundrum, but RL is consuming me & most of my brain until November 2020. These days there's only some activity at the 'copying a Bob Ross painting for therapeutic reasons' level. 😄

**Comment by GerHobbelt** [comment]
More work done in commit SHA-1: fc2449c99ac4eb0550748ae2f6a178d41ab6e466

**Comment by GerHobbelt** [comment]
Closing this one as latest change have made this "survivable" at least: these GDI+ errors are treated as non-fatal and the app continues. (While other types of "unhandled errors" are still treated as fatal, like they should.)

Not a fix per se, but a tweak to continue working / ignore the bugger as it happens semi-randomly and turns out be harmless (at least on my dev/test box)

**Comment by GerHobbelt** [comment]
Marked as "wontfix" for now as it's not really **gone**; it's just made a non-fatal, move along, nothing to see here type of error.
