### ISSUE TITLE
Associating PDF with Vanilla Reference

### ISSUE THREAD

**Issue by Wonderkitten** [jimmejardine/qiqqa-open-source#253]
Hi,

I'm not having any joy when trying to add a local PDF to a Vanilla Reference in 0.82 on Windows. I get the pop up with a dbl click, get the file browser, choose a file, but then nothing seems to happen with the underlying reference in the library (it remains vanilla, no file associated). Tried multiple files and references, both local libraries and intranet.

**Comment by GerHobbelt** [comment]
IIRC a vanilla ref always stays a vanilla ref: PDFs added to the library are keyed to their content hash and vanilla refs get keyed differently. 

The work-around for now might be to add the PDF to the library, where it should then show up as a new entry, and then copy the bibtex/annotations over from the Vanilla record to the PDF record.

I will have to look into this further when there's more time available; hope the work-around is good enough for you now.

**Comment by Wonderkitten** [comment]
Amazing, thank you so much for your prompt response. Workaround is fine for now!

**Comment by GerHobbelt** [comment]
Just announced the Qiqqa bugfix release in the qiqqa-releases mailing list
at
qiqqa-releases <qiqqa-releases@googlegroups.com>

To get notified about future releases, you can subscribe to that list:
https://groups.google.com/g/qiqqa-releases?pli=1

Bugfix release can be downloaded at
https://github.com/GerHobbelt/qiqqa-open-source/releases/tag/v82.0.7568-29227

Cheers,

Ger

**Comment by GerHobbelt** [comment]
Whoops, before I forget:

the file association works for **local files** only!

Attempting to associate a PDF "From Web" will fail to produce a
association. This has some deeper issues, which must addressed later as
that's more complex to fix.

Met vriendelijke groeten / Best regards,

Ger Hobbelt

--------------------------------------------------
web:    http://www.hobbelt.com/
        http://www.hebbut.net/
mail:   ger@hobbelt.com
mobile: +31-6-11 120 978
--------------------------------------------------
