### ISSUE TITLE
✅ .\Utilities\GUI\Brainstorm\* === .\Qiqqa\Brainstorm* ? (/Almost/ duplicate source code trees) 

### ISSUE THREAD

**Issue by GerHobbelt** [jimmejardine/qiqqa-open-source#26]
Did a tree compare after I ran into a few Code Analysis reports from MSVS: it looks like those source trees are VERY similar and one may have been a copy of the other at some time.

The question is which of the few differences in the source codes there is *leading*, i.e. which one can be thrown away?

My initial bet is on the Utilities/... one as this is quite Qiqqa UI specific stuff IMHO, but then the Brainstorm material originated from earlier days, right?...

**Comment by GerHobbelt** [comment]
diffs are reported in commit SHA-1: 2d51712e7879e956ea8c03909bf6b64595f2a047 : see code diff view

> NOTE: ... though the Qiqqa/Brainstorm/SceneManager/SceneRenderingControl.xaml.cs `node_controls.Clear()` cleanup code change wasn't exactly part of it, but due to commit SHA-1: 177a2be0cff4e92a9ae285c61c2377bac1cbf1c4 / work done on issue  https://github.com/jimmejardine/qiqqa-open-source/issues/26

**Comment by GerHobbelt** [comment]
Done as per #33:

Revision: 2d51712e7879e956ea8c03909bf6b64595f2a047
addressing https://github.com/jimmejardine/qiqqa-open-source/issues/26 : nuked the Utilities/GUI/BrainStorm copy and copied/commented all diffs into the Qiqqa source tree: every diff edit references the issue https://github.com/jimmejardine/qiqqa-open-source/issues/26 in the comments.     `Utilities/GUI/BrainStorm/` === `Qiqqa/BrainStorm/`

**Comment by GerHobbelt** [comment]
> Closing <sup>and decluttering the issue list so it stays workable for me</sup>: fixed in https://github.com/GerHobbelt/qiqqa-open-source mainline=master branch, pending #15 / any maintainer rights/actions.

**Comment by jimme-jamatto** [comment]
yeah i had originally built the brainstorm layout code specifically for qiqqa.  then over the years i needed it for other projects i did, and so pulled the brainstorm into utils, but for backwards compatibility serialization reasons, didnt want to break the existing qiqqa version.  So left a version in qiqqa.

the utilities one would have been 'more advanced' but just slightly...

**Comment by GerHobbelt** [comment]
👍 

As mentioned above, Revision: 2d51712 is where I did a complete manual code comparison of both source trees and merged the enhancements from Utilities copy into Qiqqa.

(sideways related: 💯 👍 for [Beyond Compare](https://scootersoftware.com/), which is the tool I use for this kind of job. BC has been a friend for a very long time now. :smile:)
