### ISSUE TITLE
Searching across libraries feature missing

### ISSUE THREAD

**Issue by quissicks** [jimmejardine/qiqqa-open-source#262]
Thanks to Ger for providing a new update and keeping qiqqa alive. I have just downloaded the new version and noticed that the search across libraries function availalble in the commercial verison is missing.

**Comment by GerHobbelt** [comment]
😓  Never noticed that one on the commercial version -- didn't have a use for it then. MMust have been removed when Qiqqa got open sourced or I effed up somewhere 🤔

**Comment by quissicks** [comment]
Dear Ger,
Thanks again for producing the updated version of Qiqqa. I had a commercial version of Qiqqa on my Microsoft Surface, which unfortunately has been condemned due to a buckled battery that apparently poses a fire risk, so I have now migrated to the open source version on a different machine. I have a very large database with nearly 27,000 items (with a backup size of 40.6GB) split across 10 or so libraries. It was really handy being able to search across the libraries, although most of the items (22,000) are in one folder. I have found Qiqqa absolutely fantastic – even with such an enormous database the searches are always quite quick.

Thanks,
Chris.

**Comment by GerHobbelt** [comment]
Note to self for later, while I'm hunting some stuff for #257: 
for this issue, I should into the code flow into & out of `class CrossLibrarySearchControl`.

**Comment by GerHobbelt** [comment]
@quissicks : Qiqqa already has 'search across libraries' AFAICT.

Here's how it should appear and be used:

When You start Qiqqa, when the HOME tab is active, the search box in top-right corner will search across all libraries:

![image](https://user-images.githubusercontent.com/402462/97646268-891c3d80-1a4f-11eb-8d27-beac01203170.png)

Here is an example of Qiqqa doing so, searching for the word 'panasonic' across several test libraries of mine (you MAY therefor see *apparently duplicate* results in the search results list: this can happen when a document is stored in multiple libraries):

![image](https://user-images.githubusercontent.com/402462/97646386-c97bbb80-1a4f-11eb-9f5c-6d89e36e3e08.png)

Also note that the *same search box*, but now with one of the libraries OPEN and ACTIVE (tab), will only search said library:

>
> ## NOTE
>
> You can check the greyed hint text in the search box, when it is empty, as well: that will tell you whether it will search in a single (active) library or in all libraries: this can also be observed in the screenshots.
>


![image](https://user-images.githubusercontent.com/402462/97646192-5f631680-1a4f-11eb-887f-07d82967343b.png)

Hope that helps! 

😅 
(Had forgotten about the functionality myself; only while I was working on another issue did I observe this and a quick test and code review revealed that search-across-all-libraries is already present and working in Qiqqa.)

**Comment by GerHobbelt** [comment]
@quissicks : please let me know in reply to this issue if the 'search across libraries' feature works as described above (see https://github.com/jimmejardine/qiqqa-open-source/issues/262#issuecomment-719102358-permalink) or whether we're talking about different things.

When it works, I'll be able to close this issue 😄

**Comment by GerHobbelt** [comment]
Closed as resolved after private comms.
