### ISSUE TITLE
UI error (version v83.0.7649.30836)

### ISSUE THREAD

**Issue by artdijk** [jimmejardine/qiqqa-open-source#290]
Following error occured initially during startup of the app. Later when building a new Expedition and at the same time searching in the same library.
I'll send a log file to Ger.
20210113101158:System.InvalidOperationException: De aanroep-thread moet STA zijn, omdat dit voor veel UI-onderdelen vereist is.
   bij System.Windows.Input.InputManager..ctor()
   bij System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   bij System.Windows.Input.KeyboardNavigation..ctor()
   bij System.Windows.FrameworkElement.FrameworkServices..ctor()
   bij System.Windows.FrameworkElement.EnsureFrameworkServices()
   bij System.Windows.FrameworkElement..ctor()
   bij System.Windows.Controls.Panel..ctor()
   bij Qiqqa.Documents.PDF.PDFControls.Page.Annotation.PDFAnnotationLayer..ctor(PDFRendererControlStats pdf_renderer_control_stats, Int32 page)
   bij Qiqqa.Documents.PDF.PDFControls.Page.PDFRendererPageControl.get_CanvasAnnotation()
   bij Qiqqa.Documents.PDF.PDFControls.Page.PDFRendererPageControl.PopulateNeededLayers()
   bij Qiqqa.Documents.PDF.PDFControls.Page.PDFRendererPageControl.<.ctor>b__33_0(Object o)
   bij Utilities.Misc.SafeThreadPool.UserWorkItem(WaitCallback callback, Boolean skip_at_app_shutdown)

**Comment by GerHobbelt** [comment]
STA error report has been reproduced here; there's a new release in the works that I will push out on next saturday at the latest, any 'known bugs' of that one will be listed in its release notes. Got to keep the cycle as short as possible that way as I need you (and others) to test this stuff for me as there are several issues which ever so slightly different behaviour on my machine. 😓 

Thank you for using Qiqqa and reporting back!

---

The software release will be announced in all relevant issues, so you'll get to see it immediately when you have the default github account setup which is to receive email when a comment has been added to an issue you filed.

**Comment by GerHobbelt** [comment]
Quick heads up: new release to try: https://github.com/GerHobbelt/qiqqa-open-source/releases/tag/v83.0.7655.37537

Please report anything you observe with the new release. Thanks!

**Comment by GerHobbelt** [comment]
Quick heads up: hotfix release to try: https://github.com/GerHobbelt/qiqqa-open-source/releases/tag/v83.0.7656.6401 (which fixes known issue in previous release https://github.com/GerHobbelt/qiqqa-open-source/releases/tag/v83.0.7655.37537)

Please report anything you observe with the new release. Thanks!

**Comment by artdijk** [comment]
Hi Ger. Well done, the UI error has not reappeared. v83.0.7656.6401 seems to work regarding my UI error.
You have changed some of the layouts causing higher publication labels. Also in the column list with the authors, the height per author has increased.  Not an error but you get less info on a screen.
Thanks.

**Comment by GerHobbelt** [comment]
Noted. I've been fiddling with the UI layout a bit; that 'widening' was not the intent. Next test release will have a document list that's more 'bunched up' to ensure you & I get to see a decent number of items on screen. 😄 

Closing this issue. When there's trouble, please file a new issue. Thanks!
