### ISSUE TITLE
glad to have qiqqa in github 

### ISSUE THREAD

**Issue by zhou11630** [jimmejardine/qiqqa-open-source#293]
qiqqa is the most helpful research tools for me. but in the past days it always running hard in my computer. i hope it will be better and better in the future!!

**Comment by GerHobbelt** [comment]
Thanks!

If the CPU loading persists, please ZIP your Qiqqa log files and send or email me a link to them (the ZIP file is very probably too large for attaching to email, hence better to upload it to a cloud storage, such as dropbox, and send me a link to download. Please mention qiqqa in the email Subject Line to prevent the gmail spamfilters from destroying your message, *and* mention you've sent me an email in this issue, so I know to track it down when it hasn't shown up in the inbox. (I get lots of email, so a bit of process to ensure receipt is in order.)

## Reasons why Qiqqa may load your CPU

- when you have imported many PDFs or some *large* PDFs, which will be processed by background processes for text extraction and possibly OCR to assist text extraction; 
- this extracted text is fed to the Lucene.NET search engine which is part of Qiqqa, which is another cost, so you can search your PDFs 
- any PDF that hasn't already a complete bibTeX record attached, will be further processed to *infer* a title, authors, etc. from the text
- documents' metadata may be processed in the background to provide auto-tags.

## Note

"Imported PDFs" is the words I use to describe several processes which will add PDFs to your library/libraries:
- downloading PDFs via the qiqqa Sniffer. (These are automatically added to your 'Guest' library)
- any PDFs 'discovered' on your local drive via the 'Folder Watch' feature.
- any PDFs drag & dropped onto Qiqqa.
- any PDFs explicitly loaded via the library/documents menu.

**Comment by GerHobbelt** [comment]
Thanks!
