### ISSUE TITLE
Cant highlight text 

### ISSUE THREAD

**Issue by Flugresl** [jimmejardine/qiqqa-open-source#295]
I just changed to the open source version 83 and my qiqqa is crashing very often. 
I cannot highlight any text using different coloured markers, and then the program is reported an unexpected error and shuts down.
Any suggestions?

**Comment by GerHobbelt** [comment]
The current v83.* releases are flagged as *unpublished* **test** releases for particular issues (around large & very large libraries). For now, it's best to revert back to a recent v82 release until these problems get addressed, e.g. https://github.com/GerHobbelt/qiqqa-open-source/releases/tag/v82.0.7568-29227  

(You can install any v79-v83 qiqqa release over your existing qiqqa without harm as they're all binary compatible re the qiqqa database and misc storage files.)

---

## Aside

If you like living a little dangerously 😈 there's a new v83 **test** release coming soon, which has the SORAX PDF lib taken out (finally) and replaced by bleeding edge Artefix MuPDF. I could use the help testing with that one. 😉

**Comment by Flugresl** [comment]
Thank you for the quick help, I downloaded the version you suggested and it seems to work fine😊

 

Andreas

**Comment by GerHobbelt** [comment]
Closing issue. Please file a new issue when the problem recurs. In that case, you may want to reference this issue: this can be easily done by typing `#295` (this issue's number preceeded by `#`) in the issue description.

**Comment by GerHobbelt** [comment]
FYI,

Thanks for reporting the issue! The problem has been identified today in v84 bleeding edge and has been fixed. The next experimental release will include the fix. (I'm still working on removing showstopping bugs after migrating from SORAX to `mupdf` (#7 / #9 / #136 / 209 ), so a new release with this issue fixed will take a while to arrive still. 

While this issue has been closed already, just wanted to say thanks for testing and reporting.
