### ISSUE TITLE
How much maximum the pdf file upload to the Qiqqa library

### ISSUE THREAD

**Issue by maryadi1213** [jimmejardine/qiqqa-open-source#301]

**Comment by maryadi1213** [comment]
There is a mention there are thousands pdf file can be added to library

**Comment by GerHobbelt** [comment]
I personally have a library with about 40K documents.

While there's no established upper limit, current Qiqqa has some stability
issues for specific usage patterns with very large libraries. (say bigger
than 5K documents if you have a huge number of annotations and plenty large
documents in the collection)

Work is under way to improve Qiqqa stability for these large libraries and
also increase the soft upper limit significantly. This includes work to
migrate Qiqqa to become a 64bit application but several major issues (sorax
pdf rendering, tesseract ocr lib, xulrunner webbrowser component) must be
replaced before that would become the new reality.
