### ISSUE TITLE
SpeedRead window shows no text

### ISSUE THREAD

**Issue by CyberMario63** [jimmejardine/qiqqa-open-source#307]
![image](https://user-images.githubusercontent.com/11547669/109415480-9a824180-797e-11eb-8705-4702e298a9c5.png)
As shown in the picture above, no matter what PDF I choose, SpeedRead shows up as blank. Pressing play will result in immediate stopping. Pressing play again will cause the player to play indefinitely, though no text will ever show on the screen.

All traditional methods of troubleshooting including:
-Changing PDFs
-Restarting the program
-Pressing all the buttons
-Changing what word the speedread should start from
-Updating Qiqqa version
-Clearing OCR
has resulted in failure. I cannot get this feature to work on my machine.

**Comment by GerHobbelt** [comment]
Which version are you using? v83.*? 

If yoou're running a v83 version, you might want to revert to latest v82 -- the v83 releases are experimental/test releases and have known (by now) bugs in several UI areas.

**Comment by CyberMario63** [comment]
That did fix my issue. I am now currently on the v82 release instead of v83.
