### ISSUE TITLE
I couldn't find my online qiqqa library.... the site www.Qiqqa.com is not opening ... Is the site is permanently closed.... what can I do to find my online library

### ISSUE THREAD

**Issue by emanelbanna** [jimmejardine/qiqqa-open-source#360]

**Comment by GerHobbelt** [comment]
Please see https://github.com/jimmejardine/qiqqa-open-source/issues/358#issuecomment-939384464.

Both questions are answered there -- or at least I attempted to 😄 . (Closing this as a near-duplicate; please file follow up in https://github.com/jimmejardine/qiqqa-open-source/issues/358, thanks!)
