### ISSUE TITLE
May I have old version v66s executable please?

### ISSUE THREAD

**Issue by masoud-babaei** [jimmejardine/qiqqa-open-source#371]

**Comment by GerHobbelt** [comment]
All old (commercial) Qiqqa software installers are mirrored at https://github.com/jimmejardine/qiqqa-open-source/tree/master/Qiqqa-Software-Installer-Releases --> click on the installer you wish to download, then github will show you a new page where there's a **\[Download]** button at the right side in the gray bar above "`View raw`". 

Clicking on the download button there will start the download of the selected `setupXX.exe` installer file, where XX is the two-digit (commercial) release number, e.g. 66 or 79.
