### ISSUE TITLE
After several years I returned to research; I have an older Qiqqa library which I would like restored. Can you help?

### ISSUE THREAD

**Issue by zhzyupanqui** [jimmejardine/qiqqa-open-source#420]
Hi,

I had a Qiqqa account many years ago and it would be great if you can help me recover.

The email associated was either fede_mina [at] hotmail.com or cerroaspero2014 [at] gmail.com

Thank you!

**Comment by GerHobbelt** [comment]
(Was answered by private email; closing this issue as unrecoverable.) 

Alas, the qiqqa cloud store site is no more; see also #358.

If you have old local copies / backups of your research data (qiqqa database files) from back then, we might be able to recover some or most of it, but that's about the extent to which recovery of old data is possible: if you don't have any local copies or backups any more, than the data is, regrettably, lost forever.

The main README has been updated to reflect this fact: https://github.com/jimmejardine/qiqqa-open-source#--i-had-a-commercial-qiqqa-user-account-and-web-libraries-aka-cloud-storage-can-it-be-accessed--recovered
