### ISSUE TITLE
❌Sniffer: entering search term jumps back to Google Scholar when in Browser tab

### ISSUE THREAD

**Issue by GerHobbelt** [jimmejardine/qiqqa-open-source#46]
@jimmejardine : was this once done intentionally?

HTR:

- open Sniffer
- click "Browser" tab
- enter search term (see screenshot example: "rs485")
- Qiqqa jumps back to Google Scholar tab

**This does not happen for other tabs"**, e.g. "Arxiv" remains active and shows the search result. Ditto for "Google.com" but since #44 has existed for me for 'forever' (ever since I started using Qiqqa many years ago), I had kinda hoped "Browser" tab was an alias for "Google.com" tab.

At least, this is a little confusing, particularly when you have 'https://google.com/' open in "Browser" tab at the time.
 
(User activity where this happens: when I hunt for PDF files outside Google Scholar using search criteria shaped like "pdf <subject keywords>".)

![2019-08-14 (1)](https://user-images.githubusercontent.com/402462/63008947-dda3bf00-be83-11e9-82a5-d2e0ebf5e6cf.png)

![2019-08-14 (4)](https://user-images.githubusercontent.com/402462/63009005-f4e2ac80-be83-11e9-9f8e-ce628cc89651.png)

![2019-08-14 (5)](https://user-images.githubusercontent.com/402462/63009999-dda4be80-be85-11e9-9d5a-2d9e43bd9682.png)

![2019-08-14 (3)](https://user-images.githubusercontent.com/402462/63008959-e4323680-be83-11e9-8e6b-60633c37b35f.png)

**Comment by jimmejardine** [comment]
it was intentional.  back in 2012 when i was doing my phd, google scholar was the best place to go for locating PDFs.  you are most welcome to change it to whatever you th8ink most relevant...

**Comment by GerHobbelt** [comment]
:+1: I like Google Scholar too; it's just that some times I'm looking for PDFs which are not on Scholar but only in the regular search engines. (search criteria used then: "pdf \<subject\>") 
An example is: electronic datasheets and application notes.

What I want to see is: user clicks a tab and thus selects a search engine (Scholar or otherwise), then editing either of the search fields above the WebBrowser control should send that query to the active tab. If the user wants to switch back to Scholar, (s)he can click the Scholar tab and that will behave likewise.

> I'll also see if I can make Qiqqa send current search criteria to the new tab, so that it loads the material we're currently looking for. 🤔 If there's other stuff already in there, a user might want to keep it.   Hm, maybe not such a smart idea, that last bit.   

Anyhow, the important bit is: **"click a tab, stick with that tab"** UX/behaviour of Qiqqa.

**Comment by GerHobbelt** [comment]
Decision: not changing this behaviour. Other tabs = search engines can be selected and remain selected. It's only the 'Browsing' tab that gets switched over to 'Google Search' tab when you enter a search term/text and hit ENTER in that editbox.

**Comment by GerHobbelt** [comment]
> Closing <sup>and decluttering the issue list so it stays workable for me</sup>: fixed in https://github.com/GerHobbelt/qiqqa-open-source mainline=master branch, pending #15 / any maintainer rights/actions.
